# values is a required top-level key
values:
  scaleway:
    fn::open::pulumi-stacks:
      stacks:
        project:
          stack: scaleway-projects/{stack}

  environmentVariables:
    SCW_ACCESS_KEY: ${{scaleway.project.accessKey}}
    SCW_SECRET_KEY: ${{scaleway.project.secretKey}}
    SCW_DEFAULT_PROJECT_ID: ${{scaleway.project.projectId}}
    SCW_DEFAULT_REGION: fr-par
  pulumiConfig:
    organizationId: ${{scaleway.project.organizationId}}
    projectId: ${{scaleway.project.projectId}}
