name: main
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
    tags-ignore:
      - v*
      - sdk/*
      - "**"

permissions:
  contents: read

jobs:
  updatecli:
    name: Run pulumi up
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack:
          - atriso
          - de-smet
          - hardes
          - homelab
          - homelab-test
          - hostsocials
          - vlaamsepannenkoeken
    steps:
      - name: "Checkout"
        uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0
        with:
          persist-credentials: false
      - name: "Install mise"
        uses: "jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d" # v4.2.0
        env:
          MISE_FETCH_REMOTE_VERSIONS_TIMEOUT: 30s
        with:
          version: 2026.7.14
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.33"
      - uses: "pulumi/actions@8e5e406f4007fca908480587cb9893c07090f58d" # v7.0.0
        with:
          command: up
          stack-name: ${{ matrix.stack }}
          pulumi-version: "3.255.0"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
